---
driver:
  name: docker
  env_variables:
    environment: local

platforms:
- name: ubuntu
  driver_config:
    image: ubuntu:16.04
    platform: ubuntu
    container_name: ubuntu
    instance_name: ubuntu
    provision_command:
      - apt-get install -y apt-transport-https

- name: centos
  driver_config:
    image: ansible/centos7-ansible:stable
    platform: centos
    container_name: centos
    instance_name: centos
    # provision_command:
    #   - yum -y install iproute
    # forward:
    #   - 8082:8082

provisioner:
  name: ansible_playbook
  hosts: all
  ansible_verbose: true
  ansible_verbosity: 2
  ansible_diff: true
  roles_path: ansible/roles
  playbook: ansible/playbook.yml

verifier:
  name: serverspec

suites:
  - name: default
