# https://kitchen.ci/docs/getting-started/kitchen-yml/
driver:
  name: docker

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: ubuntu-20.04
  - name: centos-7
  - name: centos-8

provisioner:
  name: ansible_playbook
  hosts: all
  ansible_binary_path: /usr/local/bin
  sudo_command: sudo -E -H
  require_chef_for_busser: false
  require_pip: <%= ENV['REQUIRE_PIP'] %>
  require_pip3: <%= ENV['REQUIRE_PIP3'] %>
  ansible_version: 4.1.0
  ansible_verbose: true
  ansible_verbosity: 2
  ansible_diff: true
  roles_path: ansible/roles
  playbook: ansible/<%= ENV['PLAYBOOK_NAME'] %>

suites:
  - name: default

transport:
  max_ssh_sessions: 6
